const ACTIONS = {
    UPDATE_SEARCH_QUERY: Symbol('UPDATE_SEARCH_QUERY'),
    GET_ENVOY_LIST: Symbol('GET_ENVOY_LIST'),
    GET_ENVOY_LIST_SUCCESS: Symbol('GET_ENVOY_LIST_SUCCESS'),
    GET_QUERY_LIST: Symbol('GET_QUERY_LIST'),
    GET_QUERY_LIST_SUCCESS: Symbol('GET_QUERY_LIST_SUCCESS'),
    GET_ENVOY_LIST_POSITIVE: Symbol('GET_ENVOY_LIST_POSITIVE'),
    GET_ENVOY_LIST_POSITIVE_SUCCESS: Symbol('GET_ENVOY_LIST_POSITIVE_SUCCESS'),
    GET_ENVOY_LIST_BY_PARTY: Symbol('GET_ENVOY_LIST_BY_PARTY'),
    GET_ENVOY_LIST_BY_PARTY_SUCCESS: Symbol('GET_ENVOY_LIST_BY_PARTY_SUCCESS'),
    GET_ENVOY_LIST_BY_POINTS: Symbol('GET_ENVOY_LIST_BY_POINTS'),
    GET_ENVOY_LIST_BY_POINTS_SUCCESS: Symbol('GET_ENVOY_LIST_BY_POINTS_SUCCESS'),
    GET_ENVOY: Symbol('GET_ENVOY'),
    GET_ENVOY_SUCCESS: Symbol('GET_ENVOY_SUCCESS'),
    GET_STRUCTURE: Symbol('GET_STRUCTURE'),
    GET_STRUCTURE_SUCCESS: Symbol('GET_STRUCTURE_SUCCESS')
}

export default ACTIONS;