const ACTIONS = {
    UPDATE_SEARCH_QUERY: Symbol('UPDATE_SEARCH_QUERY'),
    GET_ENVOY_LIST: Symbol('GET_ENVOY_LIST'),
    GET_ENVOY_LIST_SUCCESS: Symbol('GET_ENVOY_LIST_SUCCESS')
}

export default ACTIONS;